# Generated by Django 3.0.3 on 2020-05-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200515_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='message',
        ),
    ]
