# Generated by Django 3.0.3 on 2020-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productdetail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=6),
            preserve_default=False,
        ),
    ]
