# Generated by Django 3.0.3 on 2020-07-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200702_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.ProductDetail'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
